c3s:
  siteassetstore:
    cache:
      enabled: true
      max-entries: 10000
      webhook:
        secret: test123
  siteconnectionregistry:
    type: DATABASE
    # Web server example
    test.inrdiary.com:
      name: INR Diary
      type: WEB_SERVER
      url: file:///Users/petermesotten/WebFactor/Projects/INRDiary/inr-diary-website
    # DO S3 example
    dos3.chalibou.be:
      name: Chalibou
      type: S3
      url: s3://ams3.digitaloceanspaces.com/c3s/chalibou-website/
      principal: DO801YH9LBZTTZNC6QPF
      secret: tPXKvqsYDyCwhDqXzw2b+sZw2c80lBc3k4k3TT/Qqlo
    # AWS S3 example
    awss3.chalibou.be:
      name: Chalibou
      type: S3
      url: s3://s3.eu-west-1.amazonaws.com/c3s/chalibou-website/
      principal: DO801YH9LBZTTZNC6QPF
      secret: tPXKvqsYDyCwhDqXzw2b+sZw2c80lBc3k4k3TT/Qqlo
  recaptcha:
    key: 6LeUn2spAAAAADu8nEkb2XZiRSzgvoojciWW0Jt4

spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/c3s
    username: c3s
    password: c3s
    driver-class-name: com.mysql.cj.jdbc.Driver